-- Add structural and profile properties to the poles table

ALTER TABLE poles
ADD COLUMN IF NOT EXISTS height DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS density DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS inertiax DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS inertiay DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS inertiaz DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS cross_areax DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS cross_areay DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS cross_areaz DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS profile_type VARCHAR(255);
